### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Dareczin** [wojcraftinho/wojnotes#2]
https://wojnotes.vercel.app/ not working

**Comment by wojcraftinho** [comment]
I know, I forgot to deploy app. It will be available soon, I will let you know here 👍🏻 Thanks for reminder.

**Comment by wojcraftinho** [comment]
Now it's working - check it out at https://wojnotes.vercel.app/.

**Comment by wojcraftinho** [comment]
Fixed - closing #2.
